services:
  my-blog-app:
    container_name: my-blog-app
    image: my-blog-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=${DB_HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - my-blog-db
  my-blog-db:
    container_name: my-blog-db
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - my-blog-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  my-blog-db-data: {}
  pgadmin-data: {}
